#------------------------------------------------------
# Deploy Backend Infra in dev/preprod/prod (as selected)
#------------------------------------------------------
name: Deploy Backend Infra

on:
  workflow_dispatch:
    inputs:     
      env:
        type: choice
        description: Backend Infra for?
        options: 
        - dev
        - test
        - prod
  
permissions:
  id-token: write
  contents: read
  
jobs:     
  create-backend-infra-dev:
    if:  ${{(vars.CREATE_BACKEND_INFRA == 'true') }}
    runs-on: ubuntu-latest
    name: Create Backend Infra - Dev
    steps:
      - uses: actions/checkout@v3
