name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: set env files
        run :  echo "hello"
             
     
      
            
              
        
      - name: Terraform replace client_id
        env:
           client_id: ${{ secrets.azure_client_id }}
        run: sed -i """s/"client_id_value"/"$client_id"/g""" backend.tf
           
      - name: Terraform replace tenant_id
        env:
           tenant_id: ${{ secrets.azure_tenant_id }}
        run: 
             sed -i """s/"tenant_id_value"/"$tenant_id"/g""" backend.tf
           

      - name: Terraform replace  _client_secret
        env:
           client_secret: ${{ vars.azure_client_secret }}
        run:
             sed -i """s/"client_secret_value"/"$client_secret"/g""" backend.tf


      - name: Terraform replace sub_id
        env:
          subsription_id: ${{ secrets.azure_sub_id }}
        run: 
             sed -i """s/"subsription_id_value"/"$subsription_id"/g""" backend.tf
      - name: Terraform show
        run: 
             cat backend.tf
        
        
        



      - name: Terraform init
        run:
          terraform init

      - name: terraform apply
        env:
          TF_VAR_github_token: ${{ secrets.ga_token}}
        run:
          terraform apply -auto-approve
      - name: terraform destroy
        env:
          TF_VAR_github_token: ${{ secrets.ga_token}}
        run:
          terraform destroy -auto-approve
      
