name: Azure openID connect 
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:     
  resourcegroups:
    runs-on: ubuntu-latest
    name: 'Azure login'
    env:
      environment: production
    steps:  
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      - name: 'Azure login'
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
        
      
     
