name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: set env files
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
          client_id: ${{ vars.azure_client_id }}
          subsription_id: ${{ vars.azure_sub_id }}
          tenant_id: ${{ vars.azure_tenant_id }}
          client_Secret: ${{ vars.azure_client_Secret }}
          name: ${{ vars.create_backend_infra}}
        run : cat backend.tf
      
        
      - name: Terraform replace values
        run: sed -i 's/client_id_value /$client_id/g' backend.tf
           
      - name: Terraform replace valuess
        run: 
             sed -i 's/tenant_id_value /$tenant_id_id/g' backend.tf
           

      - name: Terraform replace values3
        run:
             sed -i 's/client_Secret_value /$client_Secret/g' backend.tf


      - name: Terraform replace values4
        run: 
             sed -i 's/subsription_id_value/"$subsription_id"/g' backend.tf
      - name: Terraform show
        run: 
             cat backend.tf
        
        
        



      # - name: Terraform init
      #   run:
      #     terraform init
        
      # - name: Terraform Apply
      #   run:
      
      #     terraform apply -auto-approve
