name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run:
            sed -e "s/\${client_id}/$client_id/" \
            -e "s/\${subsription_id}/$subsription_id/" \
            -e "s/\${client_secret}/$client_secret/" \
            -e "s/\${tenant_id}/$tenant_id/" \
            backend.tf.template > backend.tf



      - name: Terraform Apply
       
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
          client_id: ${{ secrets.azure_client_id }}
          subsription_id: ${{ secrets.azure_sub_id }}
          tenant_id: ${{ secrets.azure_tenant_id }}
          client_Secret: ${{ secrets.azure_client_Secret }}
        run:
          terraform init
          terraform apply -auto-approve
