name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
          client_id: ${{ secrets.azure_client_id }}
          subsription_id: ${{ secrets.azure_sub_id }}
          tenant_id: ${{ secrets.azure_tenant_id }}
          client_Secret: ${{ secrets.azure_client_Secret }}
       
        run: terraform init

      - name: Terraform Apply
       
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
          TF_VAR_client_id: ${{ secrets.azure_client_id }}
          TF_VAR_subsription_id: ${{ secrets.azure_sub_id }}
          TF_VAR_tenant_id: ${{ secrets.azure_tenant_id }}
          TF_VAR_client_Secret: ${{ secrets.azure_client_Secret }}
        run: terraform apply -auto-approve
