name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: set env files
        run :  echo "hello"
             
     
      
            
              
        
      - name: Terraform replace values
        env:
           client_id: ${{ vars.azure_client_id }}
        run: sed -i """s/"client_id_value"/"$client_id"/g""" backend.tf
           
      - name: Terraform replace valuess
        env:
           tenant_id: ${{ vars.azure_tenant_id }}
        run: 
             sed -i """s/"tenant_id_value"/"$tenant_id"/g""" backend.tf
           

      - name: Terraform replace values3
        env:
           client_Secret: ${{ vars.azure_client_Secret }}
        run:
             sed -i """s/"client_Secret_value"/"$client_Secret"/g""" backend.tf


      - name: Terraform replace values4
        env:
          subsription_id: ${{ vars.azure_sub_id }}
        run: 
             sed -i """s/"subsription_id_value"/"$subsription_id"/g""" backend.tf
      - name: Terraform show
        run: 
             cat backend.tf
        
        
        



      - name: Terraform init
        run:
          terraform init
      
