name: Terraform

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: show files
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
          client_id: ${{ secrets.azure_client_id }}
          subsription_id: ${{ secrets.azure_sub_id }}
          tenant_id: ${{ secrets.azure_tenant_id }}
          client_Secret: ${{ secrets.azure_client_Secret }}
      
        run: echo "Hello from GitHub Actions!"
      - name: Terraform Init
       
        run:
            
          sed -i \
          "s/client_id = \"\${client_id}\"/client_id = \"${client_id}\"/g" \
          "s/subscription_id = \"\${subsription_id}\"/subscription_id = \"${subscription_id}\"/g" \
          "s/tenant_id = \"\${tenant_id}\"/tenant_id = \"${tenant_id}\"/g" \
          backend.tf.template > backend.tf



      - name: Terraform Apply
       
        env:
          TF_VAR_github_token: ${{ secrets.ga_token }}
         
        run:
          terraform init
          terraform apply -auto-approve
