name: Azure openID connect 
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:     
  resourcegroups:
    runs-on: ubuntu-latest
    steps:  
      - name: 'Azure login'
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
      - name: 'Run az commands'
        run: |
          az account show
        
      
     
