name: Azure Login via azure cli

on:
  workflow_dispatch:
  #push:
    #branches: [main]

jobs:
  azure-login-and-resource-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
 
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}
     
    
      - name: cmd
        # run: |
        #     cd ./personal_testing
        #     terraform init

          
          
