name: Azure Login via azure cli

on:
  workflow_dispatch:
  #push:
    #branches: [main]

jobs:
  azure-login-and-resource-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  
     
      - name: Login to Azure using service principal
        run: |
         az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}         

      # - name: cmd
      #   run: |
      #       cd ./personal_testing
      #       terraform init

          
          
