# Deploy Core Infra in dev
#------------------------------------------
name: Deploy Core Infra
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:     
  create-core-infra:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
       # AZ CLI Login using OIDC Federated credential
      - name: Azure login - ${{ inputs.environment }}
        uses: azure/login@v2.1.0
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }} 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
      - name: Pipelines Terraform initialize
       
        run: |
            terraform init
            terraform plan
            terraform apply -auto-approve
          
      # - name: Pipelines Terraform validate
      #   env:
      #     layer: core
      #   run: |
      #     layer=${layer} make validate
          
      # - name: Pipelines Terraform plan
      #   env:
      #     layer: core
      #   run: |
      #     layer=${layer} make plan
      
