name: Build Docker Image

on:
  workflow_dispatch:
    

jobs:
  chreatiinra:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        working-directory: siesta/
        run: docker build -t my-image .
