name: secretes_with backend.tf

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-latest
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform replace  azure creds
        env:
           client_id: ${{ secrets.azure_client_id }}
           tenant_id: ${{ secrets.azure_tenant_id }}
           subsription_id: ${{ secrets.azure_sub_id }}
        run: | 
          sed -i """s/"client_id_value"/"$client_id"/g""" backend.tf
          sed -i """s/"tenant_id_value"/"$tenant_id"/g""" backend.tf 
          sed -i """s/"subsription_id_value"/"$subsription_id"/g""" backend.tf
        
        
    

      - name: terraform  init & apply & destroy
        env: 
          TF_VAR_github_token: ${{ secrets.ga_token}}
        run: |
           terraform init
           terraform apply -auto-approve
           terraform destroy -auto-approve
     
      
