name: Deploy Foundation Infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
          client-id: HI
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show
        env:
          sub_id: ${{ inputs.enviroment }}
        run :
            echo  "$sub_id"
          
        
        
        

      
