name: Deploy Foundation Infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
          client-id: HI
  
   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: show
        env:
          sub_id: ${{ input.parameter }}
        run :
            echo  "$sub_id"
          
        
        
        
    

      # - name: terraform  init & apply & destroy
      #   env: 
      #     TF_VAR_github_token: ${{ secrets.ga_token}}
      #   run: |
      #      terraform init
      #      terraform apply -auto-approve
      #      terraform destroy -auto-approve
     
      
